Repository Himedia-bootcamp/J4JG.BE, pull requests merged in 2024-08, with the labels that each got.

#22 feat: jwt를 이용하여 user정보 controller parameter로 쓸수있게 기능 추가
  build.gradle
  src/main/java/ott/j4jg_be/adapter/in/web/rest/test/SampleController.java
  src/main/java/ott/j4jg_be/application/service/jwt/JwtService.java
  src/main/java/ott/j4jg_be/common/annotation/CurrentUser.java
  src/main/java/ott/j4jg_be/config/framework/filter/CurrentUserArgumentResolver.java
  src/main/java/ott/j4jg_be/config/framework/filter/JwtFilter.java
  src/main/java/ott/j4jg_be/config/framework/web/WebConfig.java
  src/main/java/ott/j4jg_be/domain/user/UserInfo.java
Labels: ✨ Feature

#26 로그인/로그아웃, JWT, Oauth 및 닉네임 수정
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/gateway-ci.yml
  backend/build.gradle
  backend/src/main/java/ott/j4jg_be/config/framework/security/SecurityConfig.java
  build.gradle
  docker-compose.yml
  gateway/build.gradle
  gateway/src/main/java/ott/j4jg_gateway/J4jgGatewayApplication.java
  gateway/src/main/java/ott/j4jg_gateway/config/CorsConfig.java
  gateway/src/main/java/ott/j4jg_gateway/config/RedisConfig.java
  gateway/src/main/java/ott/j4jg_gateway/config/SecurityConfig.java
  gateway/src/main/java/ott/j4jg_gateway/controller/MainController.java
  gateway/src/main/java/ott/j4jg_gateway/controller/ReissueController.java
  gateway/src/main/java/ott/j4jg_gateway/controller/SuccessController.java
  gateway/src/main/java/ott/j4jg_gateway/controller/UserController.java
  gateway/src/main/java/ott/j4jg_gateway/jwt/JWTFilter.java
  gateway/src/main/java/ott/j4jg_gateway/jwt/JWTUtil.java
  gateway/src/main/java/ott/j4jg_gateway/model/dto/CustomOAuth2User.java
  gateway/src/main/java/ott/j4jg_gateway/model/dto/GoogleResponse.java
  gateway/src/main/java/ott/j4jg_gateway/model/dto/KakaoResponse.java
  gateway/src/main/java/ott/j4jg_gateway/model/dto/OAuth2Response.java
  gateway/src/main/java/ott/j4jg_gateway/model/dto/UserAddInfoDTO.java
  gateway/src/main/java/ott/j4jg_gateway/model/dto/UserAuthDTO.java
  gateway/src/main/java/ott/j4jg_gateway/model/entity/RefreshToken.java
  gateway/src/main/java/ott/j4jg_gateway/model/entity/User.java
  gateway/src/main/java/ott/j4jg_gateway/model/entity/UserAddInfo.java
  gateway/src/main/java/ott/j4jg_gateway/model/enums/USERROLE.java
  gateway/src/main/java/ott/j4jg_gateway/oauth2/CustomLogoutSuccessHandler.java
  gateway/src/main/java/ott/j4jg_gateway/oauth2/CustomSuccessHandler.java
  gateway/src/main/java/ott/j4jg_gateway/repository/RedisRefreshTokenRepository.java
  gateway/src/main/java/ott/j4jg_gateway/repository/UserAddInfoRepository.java
  gateway/src/main/java/ott/j4jg_gateway/repository/UserRepository.java
  gateway/src/main/java/ott/j4jg_gateway/service/CustomOAuth2UserService.java
  gateway/src/main/java/ott/j4jg_gateway/service/UserAddInfoService.java
  gateway/src/test/java/ott/j4jg_gateway/J4JgGatewayApplicationTests.java
  gateway/src/test/java/ott/j4jg_gateway/jwt/JWTUtilTest.java
  gateway/src/test/java/ott/j4jg_gateway/service/CustomOAuth2UserServiceTest.java
Labels: ⚙ Setting, ✨ Feature, 📬 API, ✅ Test, 🔨 Refactor, 🐞 BugFix

#28 Test Build
  backend/build.gradle
  backend/src/main/java/ott/j4jg_be/adapter/in/web/dto/mentoring/MatchingRequestDTO.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/dto/mentoring/MentoringApplicationDTO.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/dto/mentoring/MentoringDTO.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/dto/scrap/ScrapDTO.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/mapper/mentoring/MentoringApplicationMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/mapper/mentoring/MentoringMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/mapper/scrap/ScrapMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/mentoring/MatchingController.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/mentoring/MentoringController.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/scrap/ScrapController.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/test/SampleController.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/point/PointHistoryAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/scrap/ScrapPersistenceAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/UserEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/mentoring/MatchingEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/mentoring/MentoringApplicationEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/mentoring/MentoringEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/point/PointHistoryEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/scrap/ScrapEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/user/UserAddInfoEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/user/UserEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/JobEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/NewsEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/PointHistoryEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/UserEntityMappper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/mentoring/MentoringApplicationEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/mentoring/MentoringEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/scrap/ScrapEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/PointHistoryRepository.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/ScrapRepository.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/UserRepository.java
  backend/src/main/java/ott/j4jg_be/application/port/in/mentoring/MatchingUsecase.java
  backend/src/main/java/ott/j4jg_be/application/port/in/scrap/ScrapUsecase.java
  backend/src/main/java/ott/j4jg_be/application/port/out/scrap/UpdateScrapPort.java
  backend/src/main/java/ott/j4jg_be/application/service/mentoring/GetMentoringApplicationService.java
  backend/src/main/java/ott/j4jg_be/application/service/mentoring/GetMentoringService.java
  backend/src/main/java/ott/j4jg_be/application/service/mentoring/MatchingService.java
  backend/src/main/java/ott/j4jg_be/application/service/mentoring/MentoringService.java
  backend/src/main/java/ott/j4jg_be/application/service/scrap/ScrapService.java
  backend/src/main/java/ott/j4jg_be/common/e_num/USERROLE.java
  backend/src/main/java/ott/j4jg_be/config/framework/db/DataSourceConfig.java
  backend/src/main/java/ott/j4jg_be/domain/mentoring/Mentoring.java
  backend/src/main/java/ott/j4jg_be/domain/user/User.java
  backend/src/main/java/ott/j4jg_be/domain/user/UserInfo.java
  build.gradle
  gateway/build.gradle
  notification/build.gradle
Labels: ✅ Test

#29 Refactor: 각각의 모듈 jar로 생성됐던 부분 bootJar 생성
  backend/build.gradle
  build.gradle
  notification/build.gradle
Labels: 🔨 Refactor

#30 refactor: scrap 캐시 및 리펙토링진행
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/test/SampleController.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/scrap/ScrapPersistenceAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/scrap/ScrapEntity.java
  backend/src/main/java/ott/j4jg_be/application/service/jwt/JwtService.java
  backend/src/main/java/ott/j4jg_be/config/framework/cache/CacheConfig.java
  backend/src/main/java/ott/j4jg_be/config/framework/db/DataSourceInterceptor.java
  backend/src/main/java/ott/j4jg_be/domain/scrap/Scrap.java
Labels: 🔨 Refactor

#33 유저 휴대전화번호 암/복호화 및 AWS 배포 설정
  .github/workflows/ci.yml
  .github/workflows/codereview.yml
  .github/workflows/gateway-ci.yml
  .github/workflows/gateway.yml
  README.md
  docker-compose.yml
  gateway/.ebextensions/00-makerFiles.config
  gateway/.platform/nginx.conf
  gateway/Procfile
  gateway/build.gradle
  gateway/src/main/java/ott/j4jg_gateway/config/CorsConfig.java
  gateway/src/main/java/ott/j4jg_gateway/model/converter/PhoneNumberEncryptor.java
  gateway/src/main/java/ott/j4jg_gateway/model/entity/User.java
  gateway/src/main/java/ott/j4jg_gateway/oauth2/CustomSuccessHandler.java
  gateway/src/main/java/ott/j4jg_gateway/service/CustomOAuth2UserService.java
  gateway/src/test/java/ott/j4jg_gateway/model/converter/PhoneNumberEncryptorTest.java
Labels: ✨ Feature, 🌏 Deploy, ✅ Test, 🔨 Refactor

#34 Merge: backend 구현된 부분 + gateway 연결
  .gitignore
  backend/build.gradle
  backend/src/main/java/ott/j4jg_be/adapter/in/web/dto/mentoring/MentoringApplicationDTO.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/mentoring/MatchingController.java
  backend/src/main/java/ott/j4jg_be/adapter/in/web/rest/search/JobInfoSearchController.java
  backend/src/main/java/ott/j4jg_be/adapter/out/api/adapter/SearchJobInfoAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/mentoring/MatchingAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/notification/CreateNotificationAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/point/PointHistoryAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/adapter/jpa/scrap/ScrapPersistenceAdapter.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/entity/jpa/notification/NotificationEntity.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/mapper/notification/NotificationEntityMapper.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/mentoring/MentoringApplicationRepository.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/point/PointHistoryRepository.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/repository/NotificationRepository.java
  backend/src/main/java/ott/j4jg_be/adapter/out/persistence/repository/jpa/scrap/ScrapRepository.java
  backend/src/main/java/ott/j4jg_be/application/port/in/mentoring/MentoringApplicationUsecase.java
  backend/src/main/java/ott/j4jg_be/application/port/out/mentoring/MatchingPort.java
  backend/src/main/java/ott/j4jg_be/application/port/out/notification/CreateNotificationPort.java
  backend/src/main/java/ott/j4jg_be/application/service/jwt/JwtService.java
  backend/src/main/java/ott/j4jg_be/application/service/mentoring/MatchingService.java
  backend/src/main/java/ott/j4jg_be/application/service/mentoring/MentoringApplicationService.java
  backend/src/main/java/ott/j4jg_be/config/framework/PushNotificationConfig.java
  backend/src/main/java/ott/j4jg_be/config/framework/db/DataSourceConfig.java
  backend/src/main/java/ott/j4jg_be/config/framework/filter/JwtFilter.java
  backend/src/main/java/ott/j4jg_be/config/framework/security/SecurityConfig.java
  backend/src/main/java/ott/j4jg_be/config/framework/web/WebConfig.java
  backend/src/main/java/ott/j4jg_be/domain/notification/Notification.java
  backend/src/main/java/ott/j4jg_be/domain/user/User.java
  backend/src/main/resources/logback-spring.xml
  build.gradle
  elasticsearch/elasticsearch/Dockerfile
  gateway/build.gradle
  gateway/src/main/java/ott/j4jg_gateway/config/CorsConfig.java
  gateway/src/main/java/ott/j4jg_gateway/config/GatewayConfiguration.java
  gateway/src/main/java/ott/j4jg_gateway/config/SecurityConfig.java
  gateway/src/main/java/ott/j4jg_gateway/controller/ReissueController.java
  gateway/src/main/java/ott/j4jg_gateway/controller/UserController.java
  gateway/src/main/java/ott/j4jg_gateway/jwt/JWTFilter.java
  gateway/src/main/java/ott/j4jg_gateway/oauth2/CustomSuccessHandler.java
  logstash/logdata/jobinfo/jobinfo.log
Labels: ✨ Feature, 🥰 Accessibility, ✅ Test, 🔨 Refactor, 🐞 BugFix
